/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SsdButton {
        "accent": "primary" | "secondary" | "ghost" | "destructive";
        "disabled": boolean;
    }
}
export interface SsdButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsdButtonElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSsdButtonElement extends Components.SsdButton, HTMLStencilElement {
    }
    var HTMLSsdButtonElement: {
        prototype: HTMLSsdButtonElement;
        new (): HTMLSsdButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ssd-button": HTMLSsdButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SsdButton {
        "accent"?: "primary" | "secondary" | "ghost" | "destructive";
        "disabled"?: boolean;
        "onSdd_ButtonClick"?: (event: SsdButtonCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ssd-button": SsdButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ssd-button": LocalJSX.SsdButton & JSXBase.HTMLAttributes<HTMLSsdButtonElement>;
        }
    }
}
